//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartBinStatusModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeviceStatus
    {
        public System.Guid Id { get; set; }
        public string DeviceId { get; set; }
        public System.DateTime Timestamp { get; set; }
        public short Status { get; set; }
    
        public virtual Device Device { get; set; }
    }
}
