//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartBinStatusModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Device
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Device()
        {
            this.DeviceStatuses = new HashSet<DeviceStatus>();
        }
    
        public string Serial { get; set; }
        public Nullable<decimal> Latitude { get; set; }
        public Nullable<decimal> Longitude { get; set; }
        public System.DateTime ReceivedDate { get; set; }
        public Nullable<System.DateTime> DeploymentDate { get; set; }
        public string NearestIntersectionFirst { get; set; }
        public string NearestIntersectionSecond { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<bool> Reviewed { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DeviceStatus> DeviceStatuses { get; set; }
    }
}
